ci: Rm merge queue cache in `cache-cleanup.yml`
since they cannot be reused

Signed-off-by: Jiahao XU <Jiahao_XU@outlook.com>

diff --git a/.github/workflows/cache-cleanup.yml b/.github/workflows/cache-cleanup.yml
--- a/.github/workflows/cache-cleanup.yml
+++ b/.github/workflows/cache-cleanup.yml
@@ -15,13 +15,25 @@ jobs:
       - uses: actions/checkout@v3
       - name: Cleanup
         run: |
+          set -euxo pipefail
+
           gh extension install actions/gh-actions-cache
 
           export REPO="${{ github.repository }}"
 
+          # Setting this to not fail the workflow while deleting cache keys.
+          set +e
+
+          # Remove pull requests cache, since they cannot be reused
           gh pr list --state closed -L 20 --json number --jq '.[]|.number' | (
               while IFS='$\n' read -r closed_pr; do
                   BRANCH="refs/pull/${closed_pr}/merge" ./cleanup-cache.sh
+              done
+          )
+          # Remove merge queue cache, since they cannot be reused
+          gh actions-cache list -L 100 | cut -f 3 | grep 'gh-readonly-queue' | sort -u | (
+              while IFS='$\n' read -r branch; do
+                  BRANCH="$branch" ./cleanup-cache.sh
               done
           )
         env:
