Add tests-pass to gh-action.yml
Signed-off-by: Jiahao XU <30436523+NobodyXu@users.noreply.github.com>

diff --git a/.github/workflows/gh-action.yml b/.github/workflows/gh-action.yml
--- a/.github/workflows/gh-action.yml
+++ b/.github/workflows/gh-action.yml
@@ -38,3 +38,16 @@ jobs:
 
       - name: Verify successful installation - display help of installed binary
         run: rg --help
+
+  # Dummy job to have a stable name for the "all tests pass" requirement
+  tests-pass:
+    name: GHA installer test pass
+    needs:
+      - test-gha-installer
+    if: always() # always run even if dependencies fail
+    runs-on: ubuntu-latest
+    steps:
+      # fail if ANY dependency has failed or cancelled
+      - if: "contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')"
+        run: exit 1
+      - run: exit 0
