Add tests-pass install-script.yml
Signed-off-by: Jiahao XU <30436523+NobodyXu@users.noreply.github.com>

diff --git a/.github/workflows/install-script.yml b/.github/workflows/install-script.yml
--- a/.github/workflows/install-script.yml
+++ b/.github/workflows/install-script.yml
@@ -152,3 +152,18 @@ jobs:
       - name: Verify `cargo-binstall` installation
         shell: bash
         run: cargo binstall -vV
+
+  # Dummy job to have a stable name for the "all tests pass" requirement
+  tests-pass:
+    name: Install scripts test pass
+    needs:
+      - unix
+      - windows
+      - windows-bash
+    if: always() # always run even if dependencies fail
+    runs-on: ubuntu-latest
+    steps:
+      # fail if ANY dependency has failed or cancelled
+      - if: "contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')"
+        run: exit 1
+      - run: exit 0
